### ISSUE TITLE
ABILITY TO CREATE NEW C/C++ PROJECT WITH WIZARD LIKE BEFORE

### ISSUE THREAD

**Issue by Kelvin-Weksa** [rwols/CMakeBuilder#22]
please return all the options from the old tools menu especially the one to create new c/c++ project. I liked it and it was really useful and time saving. it was the main reason I was using this package!! - a wizard to create a c/c++ cmake project. we need this please!!

please get it back asap!!
alternatively, is there a way to stick to the older version?

**Comment by rwols** [comment]
Thanks for making an issue. Are you on ST3? The package doesn’t work on ST3 anymore I believe.

**Comment by rwols** [comment]
Having said that, I think I just removed the feature entirely as I didn't think it was core enough to the spirit of this package -- which is to just configure & build a project.

There is for example this alternative which probably does it better: https://github.com/friendlyanon/cmake-init

**Comment by Kelvin-Weksa** [comment]
thank you for reply. am on ST4 and this update just sneaked up on me yesterday and to my dismay that feature was not there after update. the alternative you provided does not create a sublime text project

please re consider the feature

my best

**Comment by rwols** [comment]
Fixed in https://github.com/rwols/CMakeBuilder/commit/983322ebb6389a0843adc12491f1e3330683e436. Should show up on package control in a few hours.

**Comment by Kelvin-Weksa** [comment]
![feature_still_not_there](https://user-images.githubusercontent.com/26436666/210412682-87258b1e-d050-45f4-8bf9-aea3ab5947ae.png)

feature is still missing

**Comment by Kelvin-Weksa** [comment]
hello,


> Fixed in [983322e](https://github.com/rwols/CMakeBuilder/commit/983322ebb6389a0843adc12491f1e3330683e436). Should show up on package control in a few hours.

its been more than a few days. the "fix" still does not have the create new c/c++ option plus saving the CMakeLists.txt file does not automatically configure project. cant you just revert to previous version. this new release of cmakebuilder is not as good, am not sure why it was necessary to upgrade the package
